const List<Map<String, String>> algerianWilayas = [
  {'name': 'Adrar', 'nameAr': 'أدرار'},
  {'name': 'Chlef', 'nameAr': 'الشلف'},
  {'name': 'Laghouat', 'nameAr': 'الاغواط'},
  {'name': 'Oum El Bouaghi', 'nameAr': 'أم البواقي'},
  {'name': 'Batna', 'nameAr': 'باتنة'},
  {'name': 'Béjaïa', 'nameAr': 'بجاية'},
  {'name': 'Biskra', 'nameAr': 'بسكرة'},
  {'name': 'Béchar', 'nameAr': 'بشار'},
  {'name': 'Blida', 'nameAr': 'البليدة'},
  {'name': 'Bouira', 'nameAr': 'بويرة'},
  {'name': 'Tamanrasset', 'nameAr': 'تمنراست'},
  {'name': 'Tébessa', 'nameAr': 'تبسة'},
  {'name': 'Tlemcen', 'nameAr': 'تلمسان'},
  {'name': 'Tiaret', 'nameAr': 'تيارت'},
  {'name': 'Tizi Ouzou', 'nameAr': 'تيزي وزو'},
  {'name': 'Algiers', 'nameAr': 'الجزائر'},
  {'name': 'Djelfa', 'nameAr': 'الجلفة'},
  {'name': 'Jijel', 'nameAr': 'جيجل'},
  {'name': 'Sétif', 'nameAr': 'ستيف'},
  {'name': 'Saïda', 'nameAr': 'سعيدة'},
  {'name': 'Skikda', 'nameAr': 'سكيكدة'},
  {'name': 'Sidi Bel Abbès', 'nameAr': 'سيدي بلعباس'},
  {'name': 'Annaba', 'nameAr': 'عنابة'},
  {'name': 'Guelma', 'nameAr': 'قالمة'},
  {'name': 'Constantine', 'nameAr': 'قسنطينة'},
  {'name': 'Medea', 'nameAr': 'المدية'},
  {'name': 'Mostaganem', 'nameAr': 'مستغانم'},
  {'name': 'M\'Sila', 'nameAr': 'المسيلة'},
  {'name': 'Mascara', 'nameAr': 'معسكر'},
  {'name': 'Ouargla', 'nameAr': 'ورقلة'},
  {'name': 'Oran', 'nameAr': 'وهران'},
  {'name': 'El Bayadh', 'nameAr': 'البيض'},
  {'name': 'Illizi', 'nameAr': 'إليزي'},
  {'name': 'Bordj Bou Arreridj', 'nameAr': 'برج بوعريريج'},
  {'name': 'Boumerdès', 'nameAr': 'بومرداس'},
  {'name': 'El Tarf', 'nameAr': 'الطارف'},
  {'name': 'Tindouf', 'nameAr': 'تندوف'},
  {'name': 'Tissemsilt', 'nameAr': 'تيسمسيلت'},
  {'name': 'El Oued', 'nameAr': 'الوادي'},
  {'name': 'Khenchela', 'nameAr': 'خنشلة'},
  {'name': 'Souk Ahras', 'nameAr': 'سوق أهراس'},
  {'name': 'Tipaza', 'nameAr': 'تيبازة'},
  {'name': 'Mila', 'nameAr': 'ميلة'},
  {'name': 'Aïn Defla', 'nameAr': 'عين الدفلا'},
  {'name': 'Naâma', 'nameAr': 'النعامة'},
  {'name': 'Aïn Témouchent', 'nameAr': 'عين تموشنت'},
  {'name': 'Ghardaïa', 'nameAr': 'غرداية'},
  {'name': 'Relizane', 'nameAr': 'الريزان'},
  {'name': 'Timimoun', 'nameAr': 'تيميمون'},
  {'name': 'Bordj Badji Mokhtar', 'nameAr': 'برج باجي مختار'},
  {'name': 'Ouled Djellal', 'nameAr': 'أولاد جلال'},
  {'name': 'Béni Abbès', 'nameAr': 'بني عباس'},
  {'name': 'In Salah', 'nameAr': 'إن صالح'},
  {'name': 'In Guezzam', 'nameAr': 'إن قزام'},
  {'name': 'Touggourt', 'nameAr': 'توغرت'},
  {'name': 'Djanet', 'nameAr': 'جانّت'},
  {'name': 'El M\'Ghair', 'nameAr': 'المغير'},
  {'name': 'El Meniaa', 'nameAr': 'المنيعة'},
];

const String defaultWilaya = 'Algiers';
